# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: List directory contents
      run: ls -la

    - name: Check if build.sh exists
      run: |
        if [ -f "build.sh" ]; then
          echo "build.sh exists"
        else
          echo "build.sh does not exist"
          exit 1
        fi

    - name: Check build.sh permissions
      run: ls -l build.sh

    - name: Build the binary
      run: ./build-prod.sh
